[package]
name = "react-transform"
version = "0.0.0"
edition = "2021"

[lib]
# cSpell:disable-next-line
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
convert_case = "0.6.0"
hex = "0.4.3"
indexmap = "2.7.0"
napi = { version = "2.7.0", default-features = false, features = ["napi4"] }
napi-derive = "2.7.0"
once_cell = "1.20.2"
regex = "1.11.1"
rustc-hash = "2.1.1"
serde = "1.0.217"
serde_json = { version = "1.0.134", features = ["preserve_order"] }
sha-1 = "0.10.1"
# cSpell:disable-next-line
swc_core = { version = "18.0.0", features = ["base", "ecma_codegen", "ecma_parser", "ecma_minifier", "ecma_transforms_typescript", "ecma_utils", "ecma_quote", "ecma_transforms_react", "ecma_transforms_optimization", "css_parser", "css_ast", "css_visit", "css_codegen", "__visit", "__testing_transform"] }
version-compare = "0.2.0"

# cSpell:disable-next-line
[target."cfg(all(target_arch = \"wasm32\", target_os = \"unknown\"))".dependencies.getrandom]
version = "0.2.15"
features = ["custom"]

[build-dependencies]
napi-build = "2.1.3"

[features]
noop = []
