name: pull-request-content-check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
env:
  CI: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  validate-pr-title:
    runs-on: lynx-ubuntu-24.04-xlarge #todo: use medium once its ready
    steps:
      - name: PR Conventional Commit Validation
        uses: ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["feat","fix","docs","test","refactor","chore","revert","ci","perf"]'
          add_label: "false"
