name: Test
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  merge_group:
    types: [checks_requested]
permissions:
  repository-projects: read
  contents: read
  actions: write
  pull-requests: write
  statuses: read
env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  code-style-check:
    runs-on: lynx-ubuntu-24.04-medium
    steps:
      - uses: actions/checkout@v4
        with:
          # We need full history for changeset status check
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --frozen-lockfile
      - name: Code Style Check
        run: |
          pnpm dprint check
          pnpm biome check
      - name: API Check
        run: pnpm turbo api-extractor
      - name: Changeset Check
        run: pnpm changeset status --since=origin/main

  build:
    uses: ./.github/workflows/workflow-build.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-xlarge
  test-rspeedy:
    needs: build
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-medium
      run: >
        pnpm run test
        --project rspeedy
        --project upgrade-rspeedy
        --project 'rspeedy/*'
        --reporter=github-actions
        --reporter=dot
        --reporter=junit
        --outputFile=test-report.junit.xml
        --test-timeout=50000
        --coverage
        --coverage.reporter='json'
        --coverage.reporter='text'
        --no-cache
        --logHeapUsage
        --silent
  test-react:
    needs: build
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-medium
      run: >
        pnpm
        --filter @lynx-js/react-runtime
        --filter @lynx-js/react-worklet-runtime
        --filter @lynx-js/react-transform
        run test
        --reporter=github-actions
        --reporter=dot
        --reporter=junit
        --outputFile=test-report.junit.xml
        --coverage.reporter='json'
        --coverage.reporter='text'
        --test-timeout=50000
        --no-cache
        --logHeapUsage
        --silent
  test-plugins:
    needs: build
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-medium
      run: >
        pnpm run test
        --project 'webpack/*'
        --test-timeout=50000
        --reporter=github-actions
        --reporter=dot
        --reporter=junit
        --outputFile=test-report.junit.xml
        --coverage
        --coverage.reporter='json'
        --coverage.reporter='text'
        --no-cache
        --logHeapUsage
        --silent
  test-tools:
    needs: build
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-medium
      run: >
        pnpm run test
        --project 'tools/*'
        --test-timeout=50000
        --reporter=github-actions
        --reporter=dot
        --reporter=junit
        --outputFile=test-report.junit.xml
        --coverage
        --coverage.reporter='json'
        --coverage.reporter='text'
        --no-cache
        --logHeapUsage
        --silent
  playwright-linux:
    needs: build
    uses: ./.github/workflows/workflow-test.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-xlarge
      is-web: true
      run: |
        export NODE_OPTIONS="--max-old-space-size=32768"
        export PLAYWRIGHT_JUNIT_OUTPUT_NAME=test-report.junit.xml
        pnpm --filter @lynx-js/web-tests run test --reporter='github,dot,junit,html'
  test-rust:
    uses: ./.github/workflows/rust.yml
    secrets: inherit
    with:
      runs-on: lynx-ubuntu-24.04-medium
  website:
    needs: build
    uses: ./.github/workflows/workflow-website.yml
  # Copied from https://github.com/swc-project/swc/blob/b192dc82e6a84bd30f159fb12ca8a216f41e8efb/.github/workflows/CI.yml#L491
  done:
    needs:
      - code-style-check
      - playwright-linux
      - test-plugins
      - test-react
      - test-rust
      - test-rspeedy
      - test-tools
      - website
    if: always()
    runs-on: lynx-ubuntu-24.04-medium
    name: Done
    steps:
      - run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
